microsoft/mu_feature_dfci

.azurepipelines/Matrix-Build-Job.yml

A new identifier can be used to identify published artifacts (as
of mu_devops 2.0.0 release). This change passes the packages and
targets being built to clarify artifact names.
The default value for the identifier is "Artifacts" so that is
what is being used at the moment. For example, build logs are
published under `"Logs Artifacts"`. After this change, the
identifier will be `"Logs <packages> <targets>"`.
- **Breaking change** - Will anyone …

.azurepipelines: Add support for new artifacts_identifier param

---

DfciPkg/IdentityAndAuthManager/UiSupport.c

`AllocatePool ()` takes a `UINTN` argument that specifies the size
of buffer to allocate. If the size is `0`, a buffer of size `0` is
returned.
The code modified here calls `AllocatePool ()` as follows:
`CertText    = AllocatePool (L'\0');`
The single wide-character literal `\0` has an integer value of zero.
This change updates the call to be `sizeof (L'\0')` which will
pass the bytes required to hold the character.
This will allow the buffer to hold the character in the following
assignment to the buffer:
`CertText[0] = L'\0';`
---
- …

DfciPkg/UiSupport: Fix bad size in memory alloc

---

.pytool/CISettings.py

Updates the CodeQL file filter list to include all filters found in
the repo. This will pick up filters from repos like mu_basecore.
a function in a new library class in a pre-existing module, ...
- **Tests** - Does the change include any explicit test code?
- …

.pytool/CISettings.py: Use all CodeQL filter files

---

DfciPkg/UnitTests/DfciVarLockAudit/UEFI/DfciLockTest.c
DfciPkg/UnitTests/DfciVarLockAudit/UEFI/DfciLockTestXml.c
DfciPkg/UnitTests/DfciVarLockAudit/UEFI/DfciLockTestXml.h

Change the Pass message to not be associated with an error message.
a function in a new library class in a pre-existing module, ...
- **Tests** - Does the change include any explicit test code?
- Examples: Unit tests, integration tests, robot tests, ...
- …

Update lock test pass message to avoid confusion

---

DfciPkg/SettingsManager/SettingsManagerProvider.c

Fixes #41 
1. Increase ENABLED_STRING_SIZE & USB_PORT_STATE_STRING_SIZE so that the buffer allocated can be big enough to accommodate the string of DFCI setting, otherwise the generated DFCI setting string will be truncated.
2. Remove define of ASSET_TAG_STRING_MAX_SIZE which is no longer used.
- Examples: Add a new library class, move a …

Update buffer size for string of DFCI setting

---

DfciPkg/Include/DfciSystemSettingStrings.h
DfciPkg/SettingsManager/SettingsManager.h
DfciPkg/SettingsManager/SettingsManagerCurrentSettingXml.c
DfciPkg/SettingsManager/SettingsManagerProvider.c

Refactor ProviderValueAsAscii() and remove following macros to make it can allocate buffer with right size for each setting.
Fix https://github.com/microsoft/mu_feature_dfci/issues/43
```
#define ENABLED_STRING_SIZE                (9)
#define ASSET_TAG_STRING_MAX_SIZE          (22)
#define SECURE_BOOT_ENUM_STRING_SIZE       (20)
#define SYSTEM_PASSWORD_STATE_STRING_SIZE  (30)
#define USB_PORT_STATE_STRING_SIZE         (20)
```
- **Breaking …

Refactor ProviderValueAsAscii()

---

DfciPkg/Application/DfciMenu/DfciRequest.c

Resolve issue where DFCI network refresh returns error code 400: bad request.  
For each item, place an "x" in between `[` and `]` if true. Example: `[x]`.
_(you can also check items in the GitHub UI)_
Code inspection.  Additional testing will be done by product teams.

Revert invalid change which breaks DFCI Refresh from network from "Add Test requirement for using local Refresh from Network server. (#3)"  577c811

---

DfciPkg/Include/Guid/DfciInternalVariableGuid.h

Due to how Variable Locking works the lock variable should be runtime accessible.  
Code inspection
NA

Make DFCI Lock Var Runtime accessible

---

DfciPkg/DfciManager/DfciManager.h
DfciPkg/DfciManager/DfciManager.inf
DfciPkg/DfciManager/DfciVarPolicies.c
DfciPkg/DfciPkg.dec
DfciPkg/Include/Guid/DfciInternalVariableGuid.h
DfciPkg/Include/Private/DfciVariablePolicies.h
DfciPkg/UnitTests/DfciVarLockAudit/UEFI/DfciLockTest.c
DfciPkg/UnitTests/DfciVarLockAudit/UEFI/DfciVarLockAuditTestApp.inf

Revert Variable locking change due to side effects (not locking) on some platforms. 
For each item, place an "x" in between `[` and `]` if true. Example: `[x]`.
_(you can also check items in the GitHub UI)_
CI and code inspection.  Platform testing will be performed ASAP
DFCI Feature requires Project Mu Phase Variables. If that is present, then no integration required.

Revert VarPolicy locking change

---

DfciPkg/UnitTests/DfciTests/DeviceUnderTest/SetupDUT.ps1

Originally tested on a system where the firewall was disabled, so the missing firewall entry error was not observed.  Fixes #74 
- Changes the setup script
Tested configuring a Windows Guest running in a QemuQ35Pkg VM.
N/A

Fix duplicate name error when adding second firewall rule

---

DfciPkg/IdentityAndAuthManager/AuthManagerProvision.c
DfciPkg/Library/DfciUiSupportLibNull/DfciUiSupportLibNull.c

Code comments and the library DfciUiSupportLibNull reference a function no longer used.  This removes the dead code from the NULL library, and updates comments in the active code. Fixes #75
For each item, place an "x" in between `[` and `]` if true. Example: `[x]`.
_(you can also check items in the GitHub UI)_
Not tested
N/A

Remove references to a function removed long ago

---

DfciPkg/Library/DfciV1SupportLibNull/DfciV1SupportLibNull.inf

The library class is currently `DfciSupportLib` in the INF file. This
name is not used anywhere else including consuming code and
documenation. Therefore, some packages have used the library class
name used elsewhere (`DfciV1SupportLibNull`) but that may give a
warning since the library class does not match the INF.
This changes updates the INF so the name is consistent.
There's also minor other cleanup:
- Fix `BASE_NAME` so it accurately identifies the instance
- Move `MdePkg.dec` to the beginning of the package order to allow
more specific definitions to override generic ones in `MdePkg`.
- Remove empty sections cluttering the file.
- …

DfciV1SupportLibNull: Assign actual library class

---

DfciPkg/Include/Library/DfciAssetTagSettingLib.h
DfciPkg/Include/Library/DfciGroupLib.h
DfciPkg/Include/Library/DfciSettingChangedNotificationLib.h
DfciPkg/Include/Library/DfciV1SupportLib.h

All header files should include header guards.
Some header files, such as those which define structures,
cannot be included more than once within a translation unit, as doing
so would cause a redefinition error. Such headers must be guarded to
prevent ill-effects from multiple inclusion. Similarly, if header
files include other header files, and this inclusion graph contains
a cycle, then at least one file within the cycle must contain header
guards in order to break the cycle. Because of cases like these, all
headers should be guarded as a matter of good practice, even if they
do not strictly need to be.
Furthermore, most modern compilers contain optimizations which are
triggered by header guards. If the header guard strictly conforms
to the pattern that compilers expect, then inclusions …

Add missing library header guards

---

DfciPkg/DfciPkg.dsc
ZeroTouchPkg/ZeroTouchPkg.dsc

An instance of StackCheckLib must be in each DSC to accommodate -fstack-protector and /GS flags.
a function in a new library class in a pre-existing module, ...
- **Tests** - Does the change include any explicit test code?
- Examples: Unit tests, integration tests, …

Add StackCheckLib Instances to Platform DSC Files

---

DfciPkg/UnitTests/DfciTests/Support/Robot/DFCI_Shared_Keywords.robot
DfciPkg/UnitTests/DfciTests/TestCases/DFCI_InTuneBadUpdate/run.robot
DfciPkg/UnitTests/DfciTests/TestCases/DFCI_InTuneEnroll/run.robot
DfciPkg/UnitTests/DfciTests/TestCases/DFCI_InTunePermissions/run.robot
DfciPkg/UnitTests/DfciTests/TestCases/DFCI_InTuneRollCerts/run.robot
DfciPkg/UnitTests/DfciTests/TestCases/DFCI_InTuneSettings/run.robot
DfciPkg/UnitTests/DfciTests/TestCases/DFCI_InTuneUnenroll/run.robot
DfciPkg/UnitTests/DfciTests/TestCases/DFCI_RefreshServer/run.robot
DfciPkg/UnitTests/DfciTests/TestCases/DFCI_TPM_DisableEnable/run.robot
DfciPkg/UnitTests/DfciTests/TestCases/DFCI_UnsignedSettings/run.robot

Corrects deprecation warning in Robot Framework
For each item, place an "x" in between `[` and `]` if true. Example: `[x]`.
_(you can also check items in the GitHub UI)_
- All tests were updated
Ran before change - warnings
Ran after change - no warnins
N / A

Fixes the Deprecation Warning for return in Robot Framework

---

DfciPkg/Application/DfciMenu/DfciUpdate.c

Resolve a CodeQL identified issue where an unsigned type was being checked against greater than or equal to zero.  This will always be true and thus provides no value
a function in a new library class in a pre-existing module, ...
- **Tests** - Does the change …

Update DfciUpdate.c to avoid unsigned comparison checking greater than zero

---

DfciPkg/Include/Settings/DfciSettings.h

Adding DFCI settings for two more power policies: After Power Loss, and Always on. 
- After Power Loss will boot the device back to the previous state before power loss. 
- Always on will always boot the device up to S0. 
The difference between the behaviors of the two modes is `Always On` will boot it up even if power was yanked in the shutdown state.

DfciPkg/DfciSettings.h: Add new DFCI settings

---

DfciPkg/UnitTests/DfciTests/RefreshServer/Dockerfile

Adds a command line switch to a pip command in the dockerfile.  This allows the docker image creation process to pass.
`--break-system-packages` was introduced in pip 23.0.1.
- https://pip.pypa.io/en/stable/news/#v23-0-1
a function in a new library class in a …

DfciPkg/DfciTests: fix refresh server pip failure

---

DfciPkg/UnitTests/DfciTests/TestCases/DFCI_InTuneSettings/DfciSettings.xml
DfciPkg/UnitTests/DfciTests/TestCases/DFCI_InTuneSettings/run.robot

Current base tests DCFI_IntuneSettings use the Dfci3.ProcessorSMT.Enable option for testing DFCI V3 features but this is a silicon specific option that fails on Microsoft AARCH64 platforms as it is not present. Recommend the base tests avoid use of silicon-specific features as these tests will not broadly pass.
DFCI testing on AARCH64 platform.
NA
Fixes #235

DfciPkg/DfciTests: remove silicon-specific test

---

.azurepipelines/Ubuntu-GCC5.yml

Remove ARM as a target for CI runs.
Only target AARCH64, IA32, X64 for GCC CI.
Local CI builds. 
Not Applicable since it is a CI change.

CI: Limit CI runs to AARCH64, IA32, X64.

---

DfciPkg/SettingsManager/SettingsManagerTransportXml.c
DfciPkg/UnitTests/DfciTests/TestCases/DFCI_UnsignedSettings/GenUsb.bat
pip-requirements.txt

Fix for Unsigned setting packets flow
Unsigned setting packet feature is added a while ago but no one ever used it.
In implementation of this feature I found bugs that will block it from working.
The Genusb.bat that used for creating bins and dfis were updated and the ValidateSettingsPacket
needs to be updated to proper handle unsigned packets which doesn't have a signature and do
need the enddata.
Tested by setting the DfciSettingRequest variable using bin data created from Genusb.bat, settings are configured successfully
and the toggling in frontpage changed as expected.

Fix for Unsigned setting packets flow

---

.pytool/CISettings.py

The branch is still on `release/202405` while `MU_BASECORE` is on `release/202502`. Now they are both on `release/202502`.
- Local CI
- Verify `Common/MU` resolves to `release/202502` with `stuart_ci_setup`
- N/A

CISettings.py: Update Common/MU branch to 202502

---

DfciPkg/Application/DfciMenu/DfciRequest.c

When comping with clangdwarf, the abi defaults to system v abi. The use of VA_ARG with clang, defaults to the msabi version.
Functions that use VA_ARG should be declared as EFIAPI. In this particular case, the function is internal, and was not declared with EFIAPI. Adding the missing declaration resolves the build error.
Testing while building a platform using TOOL_CHAIN_TAG=CLANGDWARF
No integration necessary

DfciPkg: DfciMenu Fix ClangDwarf compile.

---

DfciPkg/Library/DfciRecoveryLib/DfciRecoveryLib.c
DfciPkg/Library/DfciRecoveryLib/DfciRecoveryLib.inf

1. Consolidate logic for determining whether the RNG protocol is available and a secure algorithm is supported by the platform in DfciRecoveryLib.c.
2. Update the list of algorithms that are considered secure for the purposes of DFCI usage to include `gEfiRngAlgorithmArmRndr` for a DRBG via the Arm RNDR register.
Platforms producing `gEfiRngAlgorithmArmRndr` should ensure it supports NIST SP800-90B compliance as described in https://developer.arm.com/documentation/100685/0000/Overview-of-Arm-True-Random-Number-Generator--TRNG-.
- CI
- Platform test in progress
- `gEfiRngAlgorithmArmRndr` will be used if present in the RNG algorithm.

DfciPkg/DfciRecoveryLib: Add support for Arm RNDR RNG algorithm
